export const categories = [
    {
        id: 1,
        label: 'Politics',
        events: [
            { year: 2008, text: "Barack Obama is elected as the first African American President of the United States." },
            { year: 2011, text: "The Arab Spring begins, leading to widespread political change across the Middle East." },
            { year: 2014, text: "Russia annexes Crimea, leading to international condemnation and sanctions." },
            { year: 2016, text: "The United Kingdom votes to leave the European Union in a referendum (Brexit)." },
            { year: 2017, text: "Donald Trump is inaugurated as the 45th U.S. President." },
            { year: 2019, text: "Mass protests in Hong Kong call for democratic reforms and independence from China." },
            { year: 2020, text: "Joe Biden is elected President of the United States, defeating incumbent Donald Trump." },
            { year: 2022, text: "Russia invades Ukraine, leading to international conflict and sanctions against Russia." },
        ]
    },
    {
        id: 2,
        label: 'Science',
        events: [
            { year: 2012, text: "Discovery of the Higgs boson particle is confirmed by scientists at CERN." },
            { year: 2014, text: "Rosetta mission successfully lands the Philae probe on a comet." },
            { year: 2015, text: "NASA’s New Horizons mission captures close-up images of Pluto." },
            { year: 2016, text: "Gravitational waves are detected for the first time, proving Einstein's theory." },
            { year: 2018, text: "NASA's InSight mission lands on Mars to study the planet's interior." },
            { year: 2020, text: "Pfizer-BioNTech and Moderna announce highly effective COVID-19 vaccines." },
            { year: 2021, text: "The Perseverance rover successfully lands on Mars to search for signs of life." },
            { year: 2022, text: "The James Webb Space Telescope is successfully launched, providing deep space imagery." },
        ],
    },
    {
        id: 3,
        label: 'Economics',
        events: [
            { year: 2008, text: "The global financial crisis leads to a severe economic downturn worldwide." },
            { year: 2011, text: "Eurozone debt crisis deepens, with Greece on the verge of economic collapse." },
            { year: 2015, text: "China experiences a major stock market crash, impacting global markets." },
            { year: 2016, text: "India demonetizes high-denomination currency notes, affecting the economy." },
            { year: 2018, text: "U.S.-China trade tensions rise, leading to tariffs and affecting global trade." },
            { year: 2020, text: "The COVID-19 pandemic causes a global recession and unprecedented government stimulus." },
            { year: 2021, text: "Global supply chain disruptions lead to shortages and inflation in many countries." },
            { year: 2022, text: "Record inflation hits major economies, with central banks raising interest rates." },
        ]
    },
    {
        id: 4,
        label: 'Cinema',
        events: [
            { year: 2009, text: "James Cameron's 'Avatar' becomes the highest-grossing film of all time." },
            { year: 2012, text: "The Avengers is released, marking a milestone for the Marvel Cinematic Universe." },
            { year: 2013, text: "'Frozen' becomes a global phenomenon and highest-grossing animated film at the time." },
            { year: 2015, text: "'Star Wars: The Force Awakens' revitalizes the Star Wars franchise." },
            { year: 2018, text: "'Black Panther' becomes a cultural milestone and breaks box-office records." },
            { year: 2019, text: "Marvel's 'Avengers: Endgame' surpasses 'Avatar' to become the highest-grossing film." },
            { year: 2020, text: "The COVID-19 pandemic forces theaters to close, accelerating the shift to streaming." },
            { year: 2021, text: "'Spider-Man: No Way Home' becomes a box-office success amid pandemic restrictions." },
        ],
    },
    {
        id: 5,
        label: 'Technology',
        events: [
            { year: 2007, text: "Apple releases the first iPhone, revolutionizing the smartphone industry." },
            { year: 2010, text: "Apple launches the iPad, creating a new market for tablet devices." },
            { year: 2012, text: "Tesla begins mass production of the Model S electric vehicle." },
            { year: 2015, text: "Microsoft releases Windows 10, merging the desktop and mobile experience." },
            { year: 2016, text: "Google's DeepMind defeats a professional Go player, advancing AI research." },
            { year: 2018, text: "5G technology begins deployment, promising faster and more reliable connectivity." },
            { year: 2021, text: "SpaceX launches the first all-civilian mission to orbit Earth." },
            { year: 2022, text: "The Metaverse gains traction as companies develop immersive virtual worlds." },
        ],
    },
    {
        id: 6,
        label: 'Sports',
        events: [
            { year: 2008, text: "Michael Phelps wins 8 gold medals at the Beijing Olympics, breaking world records." },
            { year: 2010, text: "Spain wins the FIFA World Cup, marking their first win in tournament history." },
            { year: 2012, text: "London hosts the Olympics, with Usain Bolt setting multiple records." },
            { year: 2014, text: "Germany wins the FIFA World Cup, defeating Argentina in the final." },
            { year: 2016, text: "The Rio Olympics are held, with the United States leading in medal count." },
            { year: 2018, text: "France wins the FIFA World Cup, defeating Croatia in the final." },
            { year: 2021, text: "The Tokyo Olympics are held after being postponed due to COVID-19." },
            { year: 2022, text: "Argentina wins the FIFA World Cup in Qatar, led by Lionel Messi." },
        ],
    },
]
